version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  test:
    docker:
      - image: cimg/node:18.20-browsers
    resource_class: medium+
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Playwright Chrome browser
          command: npx playwright install chromium
      - run:
          name: Create test results directory
          command: mkdir -p test-results/playwright
      - run:
          name: Start web server in background
          command: PORT=8108 npm run dev
          background: true
      - run:
          name: Wait for web server to start
          command: |
            # Wait for the server to be available
            for i in $(seq 1 30); do
              if curl -s http://localhost:8108 > /dev/null; then
                echo "Server is up!"
                exit 0
              fi
              echo "Waiting for server... ($i/30)"
              sleep 1
            done

            echo "Server failed to start"
            exit 1
      - run:
          name: Run Playwright tests
          command: |
            PLAYWRIGHT_JUNIT_OUTPUT_NAME=test-results/playwright/junit.xml npm run test:ci:full
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_artifacts:
          path: playwright-report
          destination: playwright-report
      - store_artifacts:
          path: test-results/playwright/junit.xml
          destination: junit.xml

workflows:
  ci:
    jobs:
      - test