version: 2.1

orbs:
  node: circleci/node@7.1.0
  browser-tools: circleci/browser-tools@1.5.2

jobs:
  test:
    docker:
      - image: cimg/node:18.20-browsers
    resource_class: medium+
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - browser-tools/install-browser-tools
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps chromium
      - run:
          name: Create test results directory
          command: mkdir -p test-results/playwright
      - run:
          name: Run Playwright tests
          command: |
            PLAYWRIGHT_JUNIT_OUTPUT_NAME=test-results/playwright/junit.xml npm run test:ci:full
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_artifacts:
          path: playwright-report
          destination: playwright-report
      - store_artifacts:
          path: test-results/playwright/junit.xml
          destination: junit.xml

workflows:
  ci:
    jobs:
      - test